/*	SCCS Id: @(#)date.h	3.4	2002/02/03 */

/* This source file is generated by 'makedefs'.  Do not edit. */
#define BUILD_DATE "Thu Dec 24 17:00:00 2020"
#define BUILD_TIME (1608800400L)

#define VERSION_NUMBER 0x00000800UL
#define VERSION_FEATURES 0x183feeccUL
#define IGNORED_FEATURES 0x00800000UL
#define VERSION_SANITY1 0x44219264UL
#define VERSION_SANITY2 0xc0d28978UL

#define VERSION_STRING "0.0.8E0F1"
#define VERSION_ID \
 "Unix SlashEM Alpha Version 0.0.8E0F1 - last build Thu Dec 24 17:00:00 2020."
